const MESSAGES = {
    Commandes: {
        Admin: {
            CONFIG: {
                name: "config",
                category: 'Admin',
                aliases: ['config'],
                description: "Modifie la base de données. Valeurs possibles :\n- `logchannel` Définit le channel de log (#channel).\n- `prefix` Définit le préfixe du bot sur le serveur.\n- `welcomeMessage` Définit le message de bienvenue.",
                cooldown: 10,
                arg: true,
                usage: "config <paramètre> <valeur>",
                isUserModo: false,
                Admin: true,
                Modo: false,
            },
            EVAL: {
                name: "eval",
                category: 'Owner',
                aliases: ['eval'],
                description: "Bot Owner seulement",
                cooldown: 10,
                arg: true,
                usage: "eval <code à tester>",
                isUserModo: false,
                Admin: true,
                Modo: false,
            },
            RESTART: {
                name: "restart",
                category: 'Owner',
                aliases: ['restart', 'reload'],
                description: "Pour relancer le bot. Bot Owner seulement",
                cooldown: 10,
                arg: false,
                usage: "reload",
                isUserModo: false,
                Admin: true,
                Modo: false,
            },
            SETUP: {
                name: "setup",
                category: 'Admin',
                aliases: ['setup', 'set-up'],
                description: "Configure le bot à son arrivée sur le serveur.",
                cooldown: 30,
                arg: false,
                usage: "setup",
                isUserModo: false,
                Admin: true,
                Modo: false,
            }
        },
        Helper: {
            HELP: {
                name: "help",
                category: 'Helper',
                aliases: ['help', 'h'],
                description: "Donne la liste de toute les commandes, ou la description d'une seule.",
                cooldown: 5,
                arg: false,
                usage: "help [commande]",
                isUserModo: false,
                Admin: false,
                Modo: false,
            }
        },
        Moderation: {
            ADDXP: {
                name: "addxp",
                category: 'Moderation',
                aliases: ["addxp", "axp"],
                description: "Ajoute de l'expérience à un membre.",
                cooldown: 5,
                arg: true,
                usage: "addxp [@user] <amount>",
                isUserModo: false,
                Admin: true,
                Modo: false,
            },
            BAN: {
                name: "ban",
                category: 'Moderation',
                aliases: ["ban"],
                description: "Bannit un utilisateur.",
                cooldown: 5,
                arg: true,
                usage: "ban <@user> <raison>",
                isUserModo: true,
                Admin: true,
                Modo: false,
            },
            DELETEXP: {
                name: "deletexp",
                category: 'Moderation',
                aliases: ["deletexp", "dxp"],
                description: "Supprime de l'expérience à un membre.",
                cooldown: 5,
                arg: true,
                usage: "deletexp [@user] <amount>",
                isUserModo: false,
                Admin: true,
                Modo: false,
            },
            KICK: {
                name: 'kick',
                category: 'Moderation',
                aliases: ['kick'],
                description: 'Kick un utilisateur.',
                cooldown: 5,
                arg: true,
                usage: 'kick <@user> <raison>',
                isUserModo: true,
                Admin: false,
                Modo: true,
            },
            MUTE: {
                name: 'mute',
                category: 'Moderation',
                aliases: ['mute', 'chut'],
                description: 'Mute un utilisateur. Le temps doit être donné en a(années), w(semaines), j (jours), h (heures), m (minutes) ou s (secondes).',
                cooldown: 10,
                arg: true,
                usage: 'mute <@user> [durée] [raison]',
                isUserModo: true,
                Admin: false,
                Modo: true,
            },
            PRUNE: {
                name: "prune",
                category: "Moderation",
                aliases: ["prune", "filtre"],
                description: "Purge un salon d'un certain nombre de messages pour un user donné.",
                cooldown: 10,
                arg: true,
                usage: `prune <@user> <nombre_de_messages>\`\navec le nombre compris entre 1 et 100.\``,
                isUserModo: true,
                Admin: false,
                Modo: true,
            },
            PURGE: {
                name: "purge",
                category: "Moderation",
                aliases: ["purge", 'clear', 'clean'],
                description: "Purge un salon d'un certain nombre de messages.",
                cooldown: 10,
                arg: true,
                usage: `purge <nb_de_msgs>\` avec le nb compris entre 1 et 100.\``,
                isUserModo: false,
                Admin: false,
                Modo: true,
            },
            UNBAN: {
                name: "unban",
                category: "Moderation",
                aliases: ["unban"],
                description: "Débannit un utilisateur.",
                cooldown: 10,
                arg: true,
                usage: "unban <user_id> [raison]",
                isUserModo: false,
                Admin: true,
                Modo: false,
            },
            UNMUTE: {
                name: 'unmute',
                category: 'Moderation',
                aliases: ['unmute', 'parle'],
                description: 'Démute un utilisateur.',
                cooldown: 10,
                arg: true,
                usage: 'unmute <@user> [raison]',
                isUserModo: false,
                Admin: false,
                Modo: true,
            }
        },
        Tournaments: {
            BANNED: {
                name: "banned",
                category: 'Tournaments',
                aliases: ["banned"],
                description: "Affiche la liste des utilisateurs bannis des tournois.",
                cooldown: 10,
                arg: false,
                usage: "banned",
                isUserModo: false,
                Admin: false,
                Modo: true,
            },
            BANTOURNOI: {
                name: "bantournoi",
                category: 'Tournaments',
                aliases: ["bantournoi"],
                description: "Enlève la possibilité à un utilisateur de participer à tournoi.",
                cooldown: 5,
                arg: true,
                usage: "bantournoi <@user> <raison>",
                isUserModo: true,
                Admin: false,
                Modo: true,
            },
            CHANGEWINNERS: {
                name: "changewinners",
                category: 'Tournaments',
                aliases: ["changewinners", "cw"],
                description: "Change immédiatement le nombre de gagnants par lobby lors d'un tournoi",
                cooldown: 20,
                arg: true,
                usage: "changewinners <number>",
                isUserModo: false,
                Admin: true,
                Modo: false,
            },
            CHECK: {
                name: "check",
                category: 'Tournaments',
                aliases: ["check"],
                description: "Désigne le vainqueur du lobby. (Possibilité de désigner plusieurs équipes en même temps)\nDans le cadre d'un tournoi solo, ce sont les ID Discord des joueurs qui sont demandés.",
                cooldown: 5,
                arg: false,
                usage: "check",
                isUserModo: false,
                Admin: false,
                Modo: true,
            },
            DELETETOURNOI: {
                name: "deletetournoi",
                category: 'Tournaments',
                aliases: ["deletetournoi", "dtournoi"],
                description: "Supprime le tournoi correspondant.",
                cooldown: 30,
                arg: false,
                usage: "deletetournoi",
                isUserModo: false,
                Admin: true,
                Modo: false,
            },
            FORCEUNREGISTER: {
                name: "forceunregister",
                category: 'Tournaments',
                aliases: ["forceunregister", "funre"],
                description: "Désinscrit un utilisateur du tournoi concerné par le salon dans lequel la commande est tapée.",
                cooldown: 10,
                arg: true,
                usage: "forceunregister @user",
                isUserModo: true,
                Admin: false,
                Modo: true,
            },
            INFOS: {
                name: "infos",
                category: 'Tournaments',
                aliases: ['infos'],
                description: "Renvoie les informations d'un tournoi en temps réel.",
                cooldown: 30,
                arg: false,
                usage: "infos",
                isUserModo: false,
                Admin: false,
                Modo: false,
            },
            LIST: {
                name: 'list',
                category: 'Tournaments',
                aliases: ['list', 'liste'],
                description: 'Affiche la liste des membres inscrits au tournoi en temps réel.',
                cooldown: 10,
                arg: false,
                usage: 'list',
                isUserModo: false,
                Admin: false,
                Modo: true,
            },
            REGISTER: {
                name: "register",
                category: "Tournaments",
                aliases: ['register', 'inscription'],
                description: 'Permet de s\' inscrire à un tournoi en cours. Fonctionnel uniquement dans le salon d\'inscriptions du tournoi concerné.',
                cooldown: 60,
                arg: false,
                usage: 'register',
                isUserModo: false,
                Admin: false,
                Modo: false
            },
            SUBMIT: {
                name: "submit",
                category: "Tournaments",
                aliases: ['submit'],
                description: 'Envoie les résultats d\'un lobby. Fonctionnel uniquement dans un lobby.',
                cooldown: 30,
                arg: false,
                usage: 'submit',
                isUserModo: false,
                Admin: false,
                Modo: false
            },
            TIMER: {
                name: "timer",
                category: 'Tournaments',
                aliases: ['timer'],
                description: "Affiche le temps restant avant le tournoi.",
                cooldown: 30,
                arg: false,
                usage: "timer",
                isUserModo: false,
                Admin: false,
                Modo: false,
            },
            TOURNOI: {
                name: "tournoi",
                category: 'Tournaments',
                aliases: ['tournoi'],
                description: "Démarre un tournoi.",
                cooldown: 10,
                arg: false,
                usage: "tournoi",
                isUserModo: false,
                Admin: true,
                Modo: false,
            },
            UNBANTOURNOI: {
                name: "unbantournoi",
                category: 'Tournaments',
                aliases: ["unbantournoi"],
                description: "Rend la possibilité à un utilisateur de participer à tournoi.",
                cooldown: 10,
                arg: true,
                usage: "unbantournoi <@user> [raison]",
                isUserModo: false,
                Admin: false,
                Modo: true,
            },
            UNREGISTER: {
                name: "unregister",
                category: 'Tournaments',
                aliases: ['unregister', 'désinscription'],
                description: "Désinscrit l'utilisateur du tournoi correspondant au salon d'inscription dans lequel la commande a été faite.",
                cooldown: 120,
                arg: false,
                usage: "unregister",
                isUserModo: false,
                Admin: false,
                Modo: false,
            },
        },
        Utilitaires: {
            ANIMANGA: {
                name: "animanga",
                category: 'Utilitaires',
                aliases: ['animanga', 'anime', 'manga', 'otaku'],
                description: "Affiche des informations sur le manga ou l'animé recherché.",
                cooldown: 5,
                arg: true,
                usage: "animanga <nom_de_l'oeuvre>",
                isUserModo: false,
                Admin: false,
                Modo: false,
            },
            ALLROLES: {
                name: "allroles",
                category: 'Utilitaires',
                aliases: ['allroles', 'ar'],
                description: "Ajoute un rôle à  celui qui réagit au message sur lequel cette commande est utilisée.",
                cooldown: 10,
                arg: false,
                usage: "rolereaction",
                isUserModo: false,
                Admin: false,
                Modo: true,
            },
            DM: {
                name: "dm",
                category: 'Utilitaires',
                aliases: ['dm'],
                description: "Indique si le bot va envoyer des DM à l'utilisateur pour certaines commandes (hors DM Reaction)",
                cooldown: 2,
                arg: false,
                usage: "dm [accept/denie]",
                isUserModo: false,
                Admin: false,
                Modo: false,
            },
            DMREACTION: {
                name: "dmreaction",
                category: 'Utilitaires',
                aliases: ['dmreaction', 'dmr'],
                description: "DM celui qui réagit au message sur lequel cette commande est utilisée.",
                cooldown: 10,
                arg: false,
                usage: "dmreaction",
                isUserModo: false,
                Admin: false,
                Modo: true,
            },
            EMBED: {
                name: "embed",
                category: 'Utilitaires',
                aliases: ['embed', 'e'],
                description: "Crée une intégration selon les critères voulus.",
                cooldown: 10,
                arg: true,
                usage: "embed COULEUR, Titre, Description",
                isUserModo: false,
                Admin: false,
                Modo: true,
            },
            ID: {
                name: "id",
                category: 'Utilitaires',
                aliases: ['id'],
                description: "Renvoie l'id d'un emoji (ou sa version unicode), d'un utilisateur, d'un salon ou d'un rôle.",
                cooldown: 5,
                arg: true,
                usage: "say <emoji/@user/#salon/@rôle>",
                isUserModo: false,
                Admin: false,
                Modo: false,
            },
            LEADERBOARD: {
                name: "leaderboard",
                category: 'Utilitaires',
                aliases: ['leaderboard', 'lb', 'classement'],
                description: "Renvoie le classement du serveur par points d'expériences et par niveau.",
                cooldown: 5,
                arg: false,
                usage: "leaderboard",
                isUserModo: false,
                Admin: false,
                Modo: false,
            },
            LILO: {
                name: "lilo",
                category: 'Utilitaires',
                aliases: ['lilo'],
                description: "Recherche sur internet (moteur de recherche Lilo) les arguments fournis et renvoie les 5 premiers résultats.",
                cooldown: 5,
                arg: true,
                usage: "lilo <recherche à effectuer>",
                isUserModo: false,
                Admin: false,
                Modo: false,
            },
            NUKE: {
                name: "nuke",
                category: 'Utilitaires',
                aliases: ['nuke'],
                description: "Supprime le channel et en recrée un à l'identique.",
                cooldown: 10,
                arg: false,
                usage: "nuke",
                isUserModo: false,
                Admin: false,
                Modo: true,
            },
            PING: {
                name: "ping",
                category: 'Utilitaires',
                aliases: ['ping', 'p', 'pong'],
                description: "Renvoie pong et donne la latence.",
                cooldown: 10,
                arg: false,
                usage: "ping",
                isUserModo: false,
                Admin: false,
                Modo: false,
            },
            QWANT: {
                name: "qwant",
                category: 'Utilitaires',
                aliases: ['qwant'],
                description: "Recherche sur internet (moteur de recherche Qwant) les arguments fournis et renvoie les 5 premiers résultats.",
                cooldown: 5,
                arg: true,
                usage: "qwant <recherche à effectuer>",
                isUserModo: false,
                Admin: false,
                Modo: false,
            },
            ROLEREACTION: {
                name: "rolereaction",
                category: 'Utilitaires',
                aliases: ['rolereaction', 'rr'],
                description: "Ajoute un rôle à  celui qui réagit au message sur lequel cette commande est utilisée.",
                cooldown: 10,
                arg: false,
                usage: "rolereaction",
                isUserModo: false,
                Admin: false,
                Modo: true,
            },
            SAY: {
                name: "say",
                category: 'Utilitaires',
                aliases: ['say', 'repeat', 'rep', 'dis'],
                description: "Renvoie le message dicté par l'utilisateur.",
                cooldown: 10,
                arg: true,
                usage: "say <votre message>",
                isUserModo: false,
                Admin: false,
                Modo: false,
            },
            SMARTNUKE: {
                name: "smartnuke",
                category: 'Utilitaires',
                aliases: ['smartnuke', 'sn'],
                description: "Supprime le channel et en recrée un à l'identique, en actualisant tous les préréglages du précédent salon ainsi qu'en sauvegardant tous les messages épinglés.",
                cooldown: 10,
                arg: false,
                usage: "smartnuke",
                isUserModo: false,
                Admin: false,
                Modo: true,
            },
            STATS: {
                name: "stats",
                category: 'Utilitaires',
                aliases: ['stats'],
                description: "Envoie les statistiques du serveur.",
                cooldown: 5,
                arg: false,
                usage: "stats",
                isUserModo: false,
                Admin: false,
                Modo: false,
            },
            XP: {
                name: "xp",
                category: 'Utilitaires',
                aliases: ['xp'],
                description: "Renvoie l'expérience de l'utilisateur",
                cooldown: 10,
                arg: false,
                usage: "xp <@user>",
                isUserModo: false,
                Admin: false,
                Modo: false,
            },
            YOUTUBE: {
                name: "youtube",
                category: 'Utilitaires',
                aliases: ['youtube', 'video', 'vidéo'],
                description: "Recherche sur YouTube la vidéo recherchées et renvoie les 5 premiers résultats.",
                cooldown: 5,
                arg: true,
                usage: "youtube <nom_de_vidéo>",
                isUserModo: false,
                Admin: false,
                Modo: false,
            }
        }
    }
}

exports.MESSAGES = MESSAGES;
